### ISSUE TITLE
what's is flickr30k/1000092795.jpg ?

### ISSUE THREAD

**Issue by andyyuan78** [jazzsaxmafia/show_attend_and_tell.tensorflow#2]
envy@ub1404:/media/envy/data1t/os_prj/github/show_attend_and_tell.tensorflow$ ll flickr30k
total 222645
drwx------ 1 envy envy         0  3月 12 22:32 ./
drwx------ 1 envy envy      4096  3月 12 23:02 ../
-rw------- 1 envy envy  38318553 11月 25  2014 dataset.json
-rw------- 1 envy envy       236 11月 27  2014 readme.txt
-rw------- 1 envy envy 189659502 11月 25  2014 vgg_feats.mat

envy@ub1404:/media/envy/data1t/os_prj/github/show_attend_and_tell.tensorflow$ PYTHONPATH=/home/envy/os_pri/github/caffe/python python make_flickr_dataset.py

I0312 23:06:40.975996  5711 net.cpp:228] relu1_1 does not need backward computation.
I0312 23:06:40.976006  5711 net.cpp:228] conv1_1 does not need backward computation.
I0312 23:06:40.976017  5711 net.cpp:270] This network produces output prob
I0312 23:06:40.976057  5711 net.cpp:283] Network initialization done.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
I0312 23:06:42.111446  5711 upgrade_proto.cpp:51] Attempting to upgrade input file specified using deprecated V1LayerParameter: VGG_ILSVRC_19_layers.caffemodel
I0312 23:06:42.520989  5711 upgrade_proto.cpp:59] Successfully upgraded file specified using deprecated V1LayerParameter
Traceback (most recent call last):
  File "make_flickr_dataset.py", line 28, in <module>
    feats = cnn.get_features(unique_images, layers='conv5_3', layer_sizes=[512,14,14])
  File "/media/envy/data1t/os_prj/github/show_attend_and_tell.tensorflow/taeksoo/cnn_util.py", line 69, in get_features
    image_batch = np.array(map(lambda x: crop_image(x, target_width=self.width, target_height=self.height), image_batch_file))
  File "/media/envy/data1t/os_prj/github/show_attend_and_tell.tensorflow/taeksoo/cnn_util.py", line 69, in <lambda>
    image_batch = np.array(map(lambda x: crop_image(x, target_width=self.width, target_height=self.height), image_batch_file))
  File "/media/envy/data1t/os_prj/github/show_attend_and_tell.tensorflow/taeksoo/cnn_util.py", line 7, in crop_image
    image = skimage.img_as_float(skimage.io.imread(x)).astype(np.float32)
  File "/home/envy/.local/lib/python2.7/site-packages/skimage/io/_io.py", line 100, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/envy/.local/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/home/envy/.local/lib/python2.7/site-packages/skimage/io/_plugins/pil_plugin.py", line 46, in imread
    im = Image.open(fname)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1996, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 2] No such file or directory: 'flickr30k/1000092795.jpg'
envy@ub1404:/media/envy/data1t/os_prj/github/show_attend_and_tell.tensorflow$

**Comment by upupnoel** [comment]
when I run `make_flickr_dataset.py`, i meet with a bug saying that i don't have the module caffe, in the 
`import caffe`.
i search it in many ways but in vain, how i can fix this?

**Comment by jazzsaxmafia** [comment]
Hi. Actually in my code, I extracted the image features using Caffe framework, 
http://caffe.berkeleyvision.org/

**Comment by upupnoel** [comment]
@jazzsaxmafia  thx, i note that in your show_and_tell model exists a _Extraced FC7 data_ `feats.npy`  . does this work for show_attend_tell if i pick it directly ?

**Comment by athenspeterlong** [comment]
Hello @upupnoel , I think they are not the same since in the paper it said it will not use Fc layer (use Conv3 instead base on my memory).
